---
title: "seq_analysis"
author: "Avery Katko"
date: "July 21, 2014"
output: html_document
---

```{r}
rm(list=ls())
library(ggplot2)
library(reshape2)
library(plyr)
library(bootstrap)
#source("useful.R")
d <- read.csv("pragmods_seq.results.tsv",sep="\t")
#head(d)
```

Exclude participants that either failed manipulation check or were rejected.

```{r}
exclude <- d$assignmentstatus == "Rejected" |
  d$Answer.name_check_correct == "\"FALSE\""
sum(exclude)
mean(exclude)

d <- subset(d, exclude == FALSE)

d$Answer.choice_correct_1 <- factor(as.logical(d$Answer.choice_correct_1))
d$Answer.choice_correct_2 <- factor(as.logical(d$Answer.choice_correct_2))
d$Answer.choice_correct_3 <- factor(as.logical(d$Answer.choice_correct_3))
```

```{r}
#d2 <- melt(d,id=c("assignmentid","workerid"))
```

```{r}

g <- function(...){
  mean(as.numeric(as.logical(...)))
}

f <- function(tn,var,val){
  df <- data.frame(workerid = d$workerid,
                   seqCond = d$Answer.sequence_condition,
                   trial = factor(rep(tn,nrow(d))),
                   variable = factor(rep(var,nrow(d))),
                   value = d[val])
  names(df) <- list('id','seqCond','trial','variable','value')
  return(df)
}

d$level_1 <- factor(ifelse(d$Answer.sequence_condition == "\"1w0w1b\"",1,0))
d$level_2 <- factor(ifelse(d$Answer.sequence_condition == "\"1w0w1b\"",0,1))
d$level_3 <- factor(rep(1,nrow(d)))

trial.df <- function(tn){
  df <- data.frame(id = d$workerid,
                   seqCond = d$Answer.sequence_condition,
                   trial = factor(rep(tn,nrow(d))),
                   level = d[sprintf("level_%d",tn)],
                   item = d[sprintf("Answer.item_%d",tn)],
                   targetProp = d[sprintf("Answer.target_prop_%d",tn)],
                   distractorProp = d[sprintf("Answer.distractor_prop_%d",tn)],
                   targetPosition = d[sprintf("Answer.target_position_%d",tn)],
                   distractorPosition = d[sprintf("Answer.distractor_position_%d",tn)],
                   choice = d[sprintf("Answer.choice_%d",tn)],
                   choiceCorrect = d[sprintf("Answer.choice_correct_%d",tn)])
  names(df) <- c("id","seqCond","trial","level","item","targetProp","distractorProp",
                 "targetPosition","distractorPosition","choice","choiceCorrect")
  return(df)
}

test.df <- trial.df(1)

#d[sprintf("Answer.choice_%d",1)]

d2 <- rbind(trial.df(1),trial.df(2),trial.df(3))

aggregate(Answer.choice_correct_1 ~ Answer.sequence_condition,d,g)
aggregate(Answer.choice_correct_2 ~ Answer.sequence_condition,d,g)
aggregate(Answer.choice_correct_3 ~ Answer.sequence_condition,d,g)

t1 <- f(1,'choiceCorrect','Answer.choice_correct_1')
t2 <- f(2,'choiceCorrect','Answer.choice_correct_2')
```

```{r}
#statistics for boolean factors
l.mean <- function(...){mean(as.logical(...))}
l.theta <- function(x,xdata,na.rm=T) {l.mean(xdata[x],na.rm=na.rm)}
l.ci.low <- function(x,na.rm=T) {
  l.mean(x,na.rm=na.rm) - quantile(bootstrap(1:length(x),1000,l.theta,x,na.rm=na.rm)$thetastar,.025,na.rm=na.rm)}
l.ci.high <- function(x,na.rm=T) {
  quantile(bootstrap(1:length(x),1000,l.theta,x,na.rm=na.rm)$thetastar,.975,na.rm=na.rm) - l.mean(x,na.rm=na.rm)}

ms <- aggregate(choiceCorrect ~ seqCond + trial + level,data = d2,l.mean)
ms$cil <- aggregate(choiceCorrect ~ seqCond + trial + level, data = d2, l.ci.low)$choiceCorrect
ms$cih <- aggregate(choiceCorrect ~ seqCond + trial + level, data = d2, l.ci.high)$choiceCorrect

cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")


ggplot(data = ms, aes(x = trial, y = choiceCorrect, fill = level)) +
  geom_bar(stat = "identity", color = "black") +
  geom_errorbar(aes(ymin = choiceCorrect - cil, ymax = choiceCorrect + cih), width = 0.2) +
  facet_grid(. ~ seqCond) + 
  theme_bw() +
  scale_fill_manual(values=cbPalette)
```

```{r}
ggplot(data = subset(ms,trial != "3"), aes(x = level, y = choiceCorrect, fill = trial)) +
  geom_bar(stat = "identity", color = "black") +
  geom_errorbar(aes(ymin = choiceCorrect - cil, ymax = choiceCorrect + cih), width = 0.2) +
  facet_grid(. ~ seqCond) +
  theme_bw() +
  scale_fill_manual(values=cbPalette)
```


